name: Example Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1002088@ds.study.iitm.ac.in
        run: echo "Hello, world!"
